---
components:
  schemas:
    java_lang_Object:
      type: "object"
      properties: {}
    StationaryTouchpoint:
      type: "object"
      properties:
        address:
          type: "object"
          $ref: "#/components/schemas/Address"
        erpPointOfSaleId:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
        customers:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
        transactions:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
    Address:
      type: "object"
      properties:
        zipCode:
          type: "string"
        city:
          type: "string"
        street:
          type: "string"
        geoLong:
          type: "integer"
        geoLat:
          type: "integer"
        id:
          type: "integer"
        houseNr:
          type: "string"
    org_dieschnittstelle_ess_entities_crm_Customer:
      type: "object"
      properties:
        firstName:
          type: "string"
        lastName:
          type: "string"
        address:
          type: "object"
          $ref: "#/components/schemas/Address"
        gender:
          type: "string"
          nullable: true
          enum:
            - "M"
            - "W"
        touchpoints:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/AbstractTouchpoint"
        id:
          type: "integer"
        mobilePhoneId:
          type: "string"
        transactions:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
        email:
          type: "string"
        preferredTouchpoint:
          type: "object"
          $ref: "#/components/schemas/AbstractTouchpoint"
    org_dieschnittstelle_ess_entities_crm_CustomerTransaction:
      type: "object"
      properties:
        date:
          type: "string"
          nullable: true
        id:
          type: "integer"
        completed:
          type: "boolean"
        value:
          type: "integer"
        items:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransactionShoppingCartItem"
        touchpoint:
          type: "object"
          $ref: "#/components/schemas/AbstractTouchpoint"
        customer:
          type: "object"
          $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
    org_dieschnittstelle_ess_entities_crm_CustomerTransactionShoppingCartItem:
      type: "object"
      properties:
        productObj:
          type: "object"
          $ref: "#/components/schemas/AbstractProduct"
        erpProductId:
          type: "integer"
        campaign:
          type: "boolean"
        id:
          type: "integer"
        units:
          type: "integer"
    AbstractProduct:
      type: "object"
      properties:
        price:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
    AbstractTouchpoint:
      type: "object"
      properties:
        erpPointOfSaleId:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
        customers:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
        transactions:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
    IndividualisedProductItem:
      type: "object"
      properties:
        price:
          type: "integer"
        name:
          type: "string"
        expirationAfterStocked:
          type: "integer"
        id:
          type: "integer"
        productType:
          type: "string"
          nullable: true
          enum:
            - "BREAD"
            - "ROLL"
            - "PASTRY"
    Campaign:
      type: "object"
      properties:
        price:
          type: "integer"
        bundles:
          type: "array"
          items:
            type: "object"
            $ref: "#/components/schemas/ProductBundle"
        name:
          type: "string"
        id:
          type: "integer"
    ProductBundle:
      type: "object"
      properties:
        product:
          type: "object"
          $ref: "#/components/schemas/IndividualisedProductItem"
        id:
          type: "integer"
        units:
          type: "integer"
paths:
  /api/health:
    get:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                properties: {}
                nullable: true
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                properties: {}
                nullable: true
          description: "default response"
      operationId: "getChecks"
  /api/metrics/{registry}/{metric}:
    get:
      parameters:
        - schema:
            type: "string"
          name: "registry"
          in: "path"
          style: "simple"
          required: true
        - schema:
            type: "string"
          name: "metric"
          in: "path"
          style: "simple"
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
      operationId: "getJson_1"
    options:
      parameters:
        - schema:
            type: "string"
          name: "registry"
          in: "path"
          style: "simple"
          required: true
        - schema:
            type: "string"
          name: "metric"
          in: "path"
          style: "simple"
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
      operationId: "getMetadata"
  /api/metrics:
    get:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
      operationId: "getJson"
  /api/metrics/{registry}:
    get:
      parameters:
        - schema:
            type: "string"
          name: "registry"
          in: "path"
          style: "simple"
          required: true
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: "string"
          description: "default response"
        default:
          content:
            text/plain:
              schema:
                type: "string"
          description: "default response"
      operationId: "getText_1_2"
    options:
      parameters:
        - schema:
            type: "string"
          name: "registry"
          in: "path"
          style: "simple"
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
          description: "default response"
      operationId: "getMetadata_1"
  /api/opi/touchpoints/{id}:
    get:
      parameters:
        - schema:
            type: "integer"
          name: "id"
          in: "path"
          style: "simple"
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
          description: "default response"
      operationId: "readTouchpoint"
    delete:
      parameters:
        - schema:
            type: "integer"
          name: "id"
          in: "path"
          style: "simple"
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "boolean"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "boolean"
          description: "default response"
      operationId: "deleteTouchpoint"
  /api/opi/touchpoints:
    get:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/StationaryTouchpoint"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/StationaryTouchpoint"
          description: "default response"
      operationId: "readAllTouchpoints"
    post:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
          description: "default response"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/StationaryTouchpoint"
        required: true
      operationId: "createTouchpoint"
  /api/async/touchpoints: {}
  /api/async/touchpoints/{id}: {}
  /api/opi/products:
    get:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
      requestBody:
        content:
          application/json:
            schema:
              type: "integer"
        required: true
      operationId: "readProduct"
    delete:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "boolean"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "boolean"
          description: "default response"
      requestBody:
        content:
          application/json:
            schema:
              type: "integer"
        required: true
      operationId: "deleteProduct"
  /api/opi/products/individualized_item:
    get:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
      operationId: "readAllProducts"
    post:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/IndividualisedProductItem"
        required: true
      operationId: "createProduct"
  /api/opi/products/campaign:
    post:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Campaign"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Campaign"
          description: "default response"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/Campaign"
        required: true
      operationId: "createCampaign"
  /api/opi/products/individualized_item/{productsId}:
    put:
      parameters:
        - schema:
            type: "integer"
          name: "productsId"
          in: "path"
          style: "simple"
          required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
        default:
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
          description: "default response"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/IndividualisedProductItem"
        required: true
      operationId: "updateProduct"
info:
  version: "0.1"
  license:
    name: ""
    url: ""
  contact:
    name: ""
    url: ""
    email: ""
  title: "WebAPI for JRS, OPI and WSV exercises"
  termsOfService: ""
  description: ""
openapi: "3.0.1"