---
components:
  schemas:
    java_lang_Object:
      type: "object"
      properties: {}
    IndividualisedProductItem:
      type: "object"
      properties:
        price:
          type: "integer"
        name:
          type: "string"
        expirationAfterStocked:
          type: "integer"
        id:
          type: "integer"
        productType:
          nullable: true
          type: "string"
          enum:
          - "BREAD"
          - "ROLL"
          - "PASTRY"
    Campaign:
      type: "object"
      properties:
        price:
          type: "integer"
        bundles:
          items:
            type: "object"
            $ref: "#/components/schemas/ProductBundle"
          type: "array"
        name:
          type: "string"
        id:
          type: "integer"
    ProductBundle:
      type: "object"
      properties:
        product:
          type: "object"
          $ref: "#/components/schemas/IndividualisedProductItem"
        id:
          type: "integer"
        units:
          type: "integer"
    StationaryTouchpoint:
      type: "object"
      properties:
        address:
          type: "object"
          $ref: "#/components/schemas/Address"
        erpPointOfSaleId:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
        customers:
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
          type: "array"
        transactions:
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
          type: "array"
    Address:
      type: "object"
      properties:
        zipCode:
          type: "string"
        city:
          type: "string"
        street:
          type: "string"
        geoLong:
          type: "integer"
        geoLat:
          type: "integer"
        id:
          type: "integer"
        houseNr:
          type: "string"
    org_dieschnittstelle_ess_entities_crm_Customer:
      type: "object"
      properties:
        lastName:
          type: "string"
        firstName:
          type: "string"
        address:
          type: "object"
          $ref: "#/components/schemas/Address"
        gender:
          nullable: true
          type: "string"
          enum:
          - "M"
          - "W"
        touchpoints:
          items:
            type: "object"
            $ref: "#/components/schemas/AbstractTouchpoint"
          type: "array"
        mobilePhoneId:
          type: "string"
        id:
          type: "integer"
        transactions:
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
          type: "array"
        preferredTouchpoint:
          type: "object"
          $ref: "#/components/schemas/AbstractTouchpoint"
        email:
          type: "string"
    AbstractTouchpoint:
      type: "object"
      properties:
        erpPointOfSaleId:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
        customers:
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
          type: "array"
        transactions:
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransaction"
          type: "array"
    org_dieschnittstelle_ess_entities_crm_CustomerTransaction:
      type: "object"
      properties:
        date:
          nullable: true
          type: "string"
        id:
          type: "integer"
        completed:
          type: "boolean"
        touchpoint:
          type: "object"
          $ref: "#/components/schemas/AbstractTouchpoint"
        items:
          items:
            type: "object"
            $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_CustomerTransactionShoppingCartItem"
          type: "array"
        value:
          type: "integer"
        customer:
          type: "object"
          $ref: "#/components/schemas/org_dieschnittstelle_ess_entities_crm_Customer"
    org_dieschnittstelle_ess_entities_crm_CustomerTransactionShoppingCartItem:
      type: "object"
      properties:
        productObj:
          type: "object"
          $ref: "#/components/schemas/AbstractProduct"
        erpProductId:
          type: "integer"
        campaign:
          type: "boolean"
        id:
          type: "integer"
        units:
          type: "integer"
    AbstractProduct:
      type: "object"
      properties:
        price:
          type: "integer"
        name:
          type: "string"
        id:
          type: "integer"
openapi: "3.0.1"
paths:
  /api/health:
    get:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                nullable: true
                type: "object"
                properties: {}
        default:
          description: "default response"
          content:
            application/json:
              schema:
                nullable: true
                type: "object"
                properties: {}
      operationId: "getChecks"
      parameters: []
  /api/metrics:
    get:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
      operationId: "getJson"
      parameters: []
  /api/metrics/{registry}:
    get:
      responses:
        "200":
          description: "default response"
          content:
            text/plain:
              schema:
                type: "string"
        default:
          description: "default response"
          content:
            text/plain:
              schema:
                type: "string"
      operationId: "getText_1"
      parameters:
      - required: true
        in: "path"
        style: "simple"
        name: "registry"
        schema:
          type: "string"
    options:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
      operationId: "getMetadata"
      parameters:
      - required: true
        in: "path"
        style: "simple"
        name: "registry"
        schema:
          type: "string"
  /api/metrics/{registry}/{metric}:
    get:
      responses:
        "200":
          description: "default response"
          content:
            text/plain:
              schema:
                type: "string"
        default:
          description: "default response"
          content:
            text/plain:
              schema:
                type: "string"
      operationId: "getText_1_2"
      parameters:
      - required: true
        in: "path"
        style: "simple"
        name: "registry"
        schema:
          type: "string"
      - required: true
        in: "path"
        style: "simple"
        name: "metric"
        schema:
          type: "string"
    options:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/java_lang_Object"
      operationId: "getMetadata_1"
      parameters:
      - required: true
        in: "path"
        style: "simple"
        name: "registry"
        schema:
          type: "string"
      - required: true
        in: "path"
        style: "simple"
        name: "metric"
        schema:
          type: "string"
  /api/async/touchpoints: {}
  /api/async/touchpoints/{id}: {}
  /api/opi/products/individualized_item:
    get:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                items:
                  type: "object"
                  $ref: "#/components/schemas/IndividualisedProductItem"
                type: "array"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                items:
                  type: "object"
                  $ref: "#/components/schemas/IndividualisedProductItem"
                type: "array"
      operationId: "readAllProducts"
      parameters: []
    post:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
      operationId: "createProduct"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/IndividualisedProductItem"
      parameters: []
    delete:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
      operationId: "deleteProduct"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "integer"
      parameters: []
  /api/opi/products/campaign:
    post:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Campaign"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/Campaign"
      operationId: "createCampaign"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/Campaign"
      parameters: []
  /api/opi/products/individualized_item/{productsId}:
    put:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/IndividualisedProductItem"
      operationId: "updateProduct"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/IndividualisedProductItem"
      parameters:
      - required: true
        in: "path"
        style: "simple"
        name: "productsId"
        schema:
          type: "integer"
  /api/opi/touchpoints/{id}:
    get:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
      operationId: "readTouchpoint"
      parameters:
      - required: true
        in: "path"
        style: "simple"
        name: "id"
        schema:
          type: "integer"
    delete:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "boolean"
      operationId: "deleteTouchpoint"
      parameters:
      - required: true
        in: "path"
        style: "simple"
        name: "id"
        schema:
          type: "integer"
  /api/opi/touchpoints:
    get:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                items:
                  type: "object"
                  $ref: "#/components/schemas/StationaryTouchpoint"
                type: "array"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                items:
                  type: "object"
                  $ref: "#/components/schemas/StationaryTouchpoint"
                type: "array"
      operationId: "readAllTouchpoints"
      parameters: []
    post:
      responses:
        "200":
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: "object"
                $ref: "#/components/schemas/StationaryTouchpoint"
      operationId: "createTouchpoint"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              $ref: "#/components/schemas/StationaryTouchpoint"
      parameters: []
info:
  description: ""
  termsOfService: ""
  contact:
    email: ""
    url: ""
    name: ""
  title: "WebAPI for JRS, OPI and WSV exercises"
  license:
    url: ""
    name: ""
  version: "0.1"